Bài 1:

In [1]:
import numpy as np
from numpy.linalg import norm
A=np.array([3,-2,1,4])
B=np.array([-1,5,0,2])
C=np.array([[2,-1,3],[1,4,-2],[0,2,5]])
#a) Tính A+B và 2A + 3B
sum_AB=A+B
mul_AB=2*A+3*B
print("Câu 1.a:")
print("A + B =",sum_AB)
print("2A + 3B =",mul_AB)
#b) Tích vô hướng và góc giữa 2 vector
dot_product=np.dot(A,B)
magnitude_A=norm(A)
magnitude_B=norm(B)
cos_theta=dot_product/(magnitude_A*magnitude_B)
theta_degree=np.degrees(np.arccos(cos_theta))
print("\nCâu 1.b:")
print("Tích vô hướng A·B =", dot_product)
print("Góc giữa A và B (độ) =", round(theta_degree, 3))
#c) Tính C^T * C
CT=C.T
CTC=CT@C
print("\nCâu 1.c:")
print("C^T * C =\n", CTC)

Câu 1.a:
A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]

Câu 1.b:
Tích vô hướng A·B = -5
Góc giữa A và B (độ) = 99.594

Câu 1.c:
C^T * C =
 [[ 5  2  4]
 [ 2 21 -1]
 [ 4 -1 38]]


Bài 2:

In [2]:
M=np.array([[2,-1,3,0],[1,4,-2,5],
              [0,2,6,-3],[-1,0,1,4]])
N=np.array([[1,3,-2,0],[4,-1,5,2],
              [0,2,3,-1],[-3,1,0,4]])
#a) Tích M x N
product=M@N
print("Câu 2.a: Tích M x N:\n",product)
#b) Định thức của M
det_M=np.linalg.det(M)
print("\nCâu 2.b: Định thức của M =",det_M)
if abs(det_M)<1e-10:
    print("M không khả nghịch vì định thức gần bằng 0")
#c) Hạng của N
rank_N=np.linalg.matrix_rank(N)
print("\nCâu 2.c: Hạng của N =", rank_N)

Câu 2.a: Tích M x N:
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

Câu 2.b: Định thức của M = 409.00000000000017

Câu 2.c: Hạng của N = 4


Bài 3:

In [3]:
P=np.array([[3,-1,0,2],[1,4,-2,0],
              [0,1,5,-1],[2,0,1,3]])
b=np.array([6,8,3,7])
#a) Ma trận nghịch đảo P
try:
    P_inv=np.linalg.inv(P)
    print("Câu 3.a: Ma trận nghịch đảo của P:\n",P_inv)
except np.linalg.LinAlgError:
    print("Câu 3.a: Ma trận P không khả nghịch")
#b) Giải hệ phương trình bằng ma trận nghịch đảo
x=P_inv@b
print("\nCâu 3.b: Nghiệm x của hệ phương trình là:\n",x)
#c) Kiểm tra nghiệm
check=P@x
print("\nCâu 3.c: P @ x =\n",check)
print("Vector b =",b)

Câu 3.a: Ma trận nghịch đảo của P:
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]

Câu 3.b: Nghiệm x của hệ phương trình là:
 [2.         1.71428571 0.42857143 0.85714286]

Câu 3.c: P @ x =
 [6. 8. 3. 7.]
Vector b = [6 8 3 7]


Bài 4:

In [4]:
Q=np.array([[5,-2,1],[0,3,-1],[2,0,4]])
#a) Giá trị riêng và vector riêng
eigenvalues,eigenvectors=np.linalg.eig(Q)
print("Câu 4.a: Giá trị riêng của Q:\n",eigenvalues)
print("\nCâu 4.b: Các vector riêng (cột tương ứng):\n",eigenvectors)
#c) Chuẩn hóa vector riêng
normed_vectors=eigenvectors/np.linalg.norm(eigenvectors,axis=0)
print("\nCâu 4.c: Vector riêng chuẩn hóa:\n",normed_vectors)

Câu 4.a: Giá trị riêng của Q:
 [6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]

Câu 4.b: Các vector riêng (cột tương ứng):
 [[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]

Câu 4.c: Vector riêng chuẩn hóa:
 [[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]


Bài 5:

In [5]:
R=np.array([[4,-1,2],[1,3,-2],[0,2,5]])
b=np.array([12,5,9])
#a) Giải hệ Rx = b
x=np.linalg.solve(R,b)
print("Câu 5.a: Nghiệm của hệ Rx = b:\n",x)
#b) Kiểm tra khả nghịch và tính nghịch đảo
try:
    R_inv=np.linalg.inv(R)
    x2=R_inv@b
    print("\nCâu 5.b: Ma trận nghịch đảo của R:\n",R_inv)
    print("Nghiệm giải bằng R^(-1):\n",x2)
    print("So sánh hai nghiệm giống nhau:",np.allclose(x,x2))
except np.linalg.LinAlgError:
    print("\nMa trận R không khả nghịch")
#c) Chuẩn Frobenius
fro_norm=np.linalg.norm(R,'fro')
print("\nCâu 5.c: Chuẩn Frobenius của R:",fro_norm)

Câu 5.a: Nghiệm của hệ Rx = b:
 [2.78823529 1.52941176 1.18823529]

Câu 5.b: Ma trận nghịch đảo của R:
 [[ 0.22352941  0.10588235 -0.04705882]
 [-0.05882353  0.23529412  0.11764706]
 [ 0.02352941 -0.09411765  0.15294118]]
Nghiệm giải bằng R^(-1):
 [2.78823529 1.52941176 1.18823529]
So sánh hai nghiệm giống nhau: True

Câu 5.c: Chuẩn Frobenius của R: 8.0
