Đề Thi Thử Thực Hành Đại Số Tuyến Tính

Bài 1:

In [3]:
import numpy as np
from numpy.linalg import norm
A=np.array([2,-1,3,0])
B=np.array([1,4,-2,5])
C=np.array([[1,2,-1],[0,3,4],[2,-1,0]])
#a)Tổng A + B và tích số 3A - 2B
sum_AB=A+B
mul_AB=3*A-2*B
print("Câu 1.a:")
print("A+B=",sum_AB)
print("3A-2B=",mul_AB)
#b)Tích vô hướng và góc giữa hai vector
dot_product=np.dot(A, B)
magnitude_A=norm(A)
magnitude_B=norm(B)
cos_theta=dot_product/(magnitude_A*magnitude_B)
theta_degree=np.degrees(np.arccos(cos_theta))
print("\nCâu 1.b:")
print("Tích vô hướng A·B=",dot_product)
print("Góc giữa A và B (độ)=",round(theta_degree, 3))
#c)Tính C^T C
CT=C.T
CTC=CT@C
print("\nCâu 1.c:")
print("C^T * C =\n",CTC)

Câu 1.a:
A + B = [3 3 1 5]
3A - 2B = [  4 -11  13 -10]

Câu 1.b:
Tích vô hướng A · B = -8
Góc giữa A và B (độ) = 108.376

Câu 1.c:
C^T * C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


Bài 2:

In [4]:
import numpy as np
M=np.array([[1,2,3,0],[4,5,6,1],[7,8,9,2],[0,1,1,0]])
N=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
#a)Tính tích M x N
product=M@N
print("a) Tích M x N:\n",product)
#b)Định thức của M
try:
    det_M=np.linalg.det(M)
    print("\nb) Định thức của M:",det_M)
except np.linalg.LinAlgError:
    print("\nb) M không khả nghịch vì không là ma trận vuông.")
#c)Tính hạng của N
rank_N=np.linalg.matrix_rank(N)
print("\nc) Hạng của N:",rank_N)

a) Tích M x N:
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

b) Định thức của M: 6.66133814775094e-16

c) Hạng của N: 2


Bài 3:

In [5]:
P=np.array([[2,1,0,1],[0,3,1,-1],[1,0,4,2],[0,1,0,3]])
b=np.array([4,7,9,5])
#a) Tìm nghịch đảo của P
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P:\n", P_inv)
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch")
#b) Giải hệ phương trình bằng nghịch đảo
x=P_inv@b
print("\nb) Nghiệm x của hệ phương trình là:\n",x)
#c)Kiểm tra nghiệm
check=P@x
print("\nc) Kiểm tra P @ x =\n", check)
print("Vector b = ",b)

a) Ma trận nghịch đảo của P:
 [[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]

b) Nghiệm x của hệ phương trình là:
 [0.46511628 2.10465116 1.65116279 0.96511628]

c) Kiểm tra P @ x =
 [4. 7. 9. 5.]
Vector b =  [4 7 9 5]


Bài 4:

In [6]:
Q=np.array([[4,-1,0],[1,3,-2],[0, 1, 2]])
#a) Giá trị riêng
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("a) Giá trị riêng của Q:\n", eigenvalues)
#b) Vector riêng
print("\nb) Các vector riêng (cột tương ứng):\n", eigenvectors)
#c) Chuẩn hóa các vector riêng
from numpy.linalg import norm
normed_vectors=np.array([v/norm(v) for v in eigenvectors.T]).T
print("\nc) Vector riêng chuẩn hóa:\n",normed_vectors)

a) Giá trị riêng của Q:
 [3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]

b) Các vector riêng (cột tương ứng):
 [[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743-0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]

c) Vector riêng chuẩn hóa:
 [[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743+0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]


Bài 5:

In [7]:
R=np.array([[1,-2,3],[2,0,1],[-1,1,4]])
b=np.array([10,8,7])
#a) Giải hệ Rx = b
x = np.linalg.solve(R, b)
print("a) Nghiệm của hệ Rx = b:\n",x)
#b) Kiểm tra khả nghịch, giải lại bằng nghịch đảo
try:
    R_inv=np.linalg.inv(R)
    x2=R_inv@b
    print("\nb) Ma trận nghịch đảo của R:\n", R_inv)
    print("Nghiệm giải bằng R^(-1):\n", x2)
    print("So sánh hai nghiệm giống nhau:", np.allclose(x, x2))
except np.linalg.LinAlgError:
    print("\nMa trận R không khả nghịch")
#c) Chuẩn Frobenius
fro_norm=np.linalg.norm(R,'fro')
print("\nc) Chuẩn Frobenius của R:", fro_norm)

a) Nghiệm của hệ Rx = b:
 [2.7826087  0.04347826 2.43478261]

b) Ma trận nghịch đảo của R:
 [[-0.04347826  0.47826087 -0.08695652]
 [-0.39130435  0.30434783  0.2173913 ]
 [ 0.08695652  0.04347826  0.17391304]]
Nghiệm giải bằng R^(-1):
 [2.7826087  0.04347826 2.43478261]
So sánh hai nghiệm giống nhau: True

c) Chuẩn Frobenius của R: 6.082762530298219
