CHƯƠNG 5: ĐỊNH THỨC, MA TRẬN VÀ ỨNG DỤNG


1. Sử dụng array và matrix trong numpy

1.1. Thông tin tóm gọn

In [25]:
import numpy as np
D=np.array([[1,2],[3,4]])
np.copyto(E,D)

* Lỗi NameError: name 'E' is not defined. Vì mảng E chưa được khởi tạo trước khi gọi np.copyto

In [26]:
E=np.array([[1, 2], [3, 5]])
np.copyto(E, D)
print(E)

[[1 2]
 [3 4]]


1.2.
Nên và không nên sử dụng kiểu dữ liệu numpy.matrix

In [ ]:
x=np.array([['a','b'],['c','d']])
y='x'
C=np.matrix([[x,y],[1, 2]] )
print(C)
#Không thể sử dụng kiểu numpy.matrix

In [32]:
#Thay np.matrix thành np.array
x=np.array([['a','b'],['c','d']])
y='x'
C=np.array([[x, y], [1, 2]], dtype=object)
print(C)

[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]


In [ ]:
A=np.matrix([[[1,2],[3,4]],[[5,6],[7,8]]])

ValueError: matrix must be 2-dimensional

In [29]:
A=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


1.3.
Đối tượng matrix từ các hàm trong gói numpy.matlib

In [30]:
from numpy import matlib
G=matlib.identity(5)
print(G)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
H=matlib.randn(3,2)
print(H)

[[ 1.6072307   1.11540162]
 [ 1.77011063  0.1840996 ]
 [-1.72474618 -0.58452671]]


In [33]:
K=matlib.zeros([4,4])
print(K)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2. Ứng dụng 2 –Liên phân số và số  π

2.1. Liên phân số

2.2. Liên phân số biểu diễn số π

In [38]:
import numpy as np
c=[3,7,15,1,292,1,1,1,2,1,3,1,14,2]
#Lỗi ko dùng np.mat thì numpy 2.0 nên đổi thành np.asmatrix
M=np.asmatrix([[1,2],[3,4]])  #khởi tạo ma trận 2x2
for i in range(len(c)):
  ci=np.asmatrix([[1,1],[1,0]])
  ci[0,0]=c[i]
  if (i==0):
    M=ci
  else:
    M=M.dot(ci)
print(M)
print (M[0,0]/M[1,0])  #in số Pi theo dãy số  biểu diễn liên phân số

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


3. Về phân tích hồi quy tuyến tính

3.1.
Dẫn nhập: khái niệm về sai số

3.2. Phương pháp bình phương cực tiểu (mô hình tuyến tính)

In [40]:
import numpy as np
X=np.array([[1,1],[1,2],[1,3],[1,4],[1,5]])
Y=np.array([[1],[2],[4],[4],[6]])
#Tính chuyển vị X^T
XT=X.T
#Tính các giá trị trung gian A1 và A2
A1=np.linalg.inv(XT.dot(X))   #[(X^T)*X]^(-1)
A2=XT.dot(Y)                  #(X^T)*Y
#Tính nghiệm A của hệ (a0, a1)
A=A1.dot(A2)
#In phương trình hồi quy gần đúng
print("Phương trình gần đúng là: y = {:.3f} + {:.3f}x".format(A[0,0], A[1,0]))
#Tính sai số tổng bình phương
Y_du_doan = X.dot(A)
sai_so = Y - Y_du_doan
tong_sai_so_binh_phuong = np.sum(sai_so ** 2)
print("Tổng bình phương sai số:", tong_sai_so_binh_phuong)

Phương trình gần đúng là: y = -0.200 + 1.200x
Tổng bình phương sai số: 0.8000000000000003


BÀI TẬP CHƯƠNG 05


In [47]:
import numpy as np
def bpcuctieu(a):
    b=[]
    o1=[]
    for i in range(len(a)):
        o1.append(1.0)
        #b.append(i*1.0) (x=0,1,2,3,4. Kết quả ra y=10.2-1.9x)
        b.append((i+1)*1.0) #x=1,2,3,4,5. Kết quả ra y=12.1-1.9x
    x=np.array([o1,b]) #tạo ma trận 2 hàng, 5 cột
    u=np.dot(x,x.T) #nhân theo chiều ngược lại: x x^T
    y=np.array(a)
    from numpy import linalg
    u_1=np.linalg.inv(u)
    v=np.dot(u_1,x)
    A=np.dot(v,y)
    return A
dulieu=[10.0,8,7,5,2]
A=bpcuctieu(dulieu)
print("Phương trình: y={:.1f}+{:.1f}x".format(A[0],A[1]))

Phương trình: y=12.1+-1.9x
