Bài thực hành chương 2

Bài 1

In [2]:
def scale(a, v):
  return [a*vi for vi in v]
v = [3,5,7]
scale(10, v)
print(scale(10,v))

[30, 50, 70]


In [3]:
def sumvector(v, w):
  return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6]
sumvector(v, w)
print(sumvector(v,w))

[5, 9, 13]


In [4]:
def dotvector(v, w):
  return sum([vi*wi for (vi, wi) in zip(v, w)])
dotvector(v, w)
print(dotvector(v,w))

68


In [5]:
def lenvector(v):
  return dotvector(v,v)
lenvector(w)
print(lenvector(w))

56


Bài 2


In [6]:
import numpy as np
scores=np.array([-1,1,2,-3,5,-4])
print(scores)
print(scores>=0)
print(scores<0)
a=np.select([scores>=0,scores<0],['so duong','so am'],default='')
print(a)

[-1  1  2 -3  5 -4]
[False  True  True False  True False]
[ True False False  True False  True]
['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']


In [7]:
scores=np.array([-1,1,2,0,-3,5,0,-4])
b=np.select([scores>0,scores==0,scores<0],['so duong','so 0','so am'],default='')
print(b)

['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


Bài 3


Bài 3.1


In [8]:
import numpy as np
from scipy import linalg, sparse
D=np.asmatrix([[3,4],[5,6] ])
print(D)

[[3 4]
 [5 6]]


In [9]:
C=np.asmatrix(np.random.random((5,7)))
print(C)

[[0.13739434 0.98064149 0.87825556 0.77509565 0.12438672 0.85164758
  0.21234401]
 [0.55921593 0.54981243 0.33643332 0.71120963 0.16369643 0.18538564
  0.67104465]
 [0.85131964 0.95242655 0.44759132 0.52461521 0.94342346 0.36887511
  0.32636496]
 [0.80965418 0.45343219 0.02103998 0.21417901 0.50262261 0.98674642
  0.72937701]
 [0.08236802 0.88864263 0.68101477 0.52663015 0.20705043 0.15457146
  0.03310586]]


In [10]:
A=np.asmatrix(np.random.random((2,2)))
print(A)

[[0.33835469 0.74853366]
 [0.49390229 0.72355033]]


In [11]:
b=np.array([(1+5j, 2j, 3j),(4, 5, 6)])
B=np.asmatrix(b)
print(b)
print(B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [12]:
print(A.T)
print(A.I)

[[0.33835469 0.49390229]
 [0.74853366 0.72355033]]
[[-5.79369372  5.99374307]
 [ 3.95483009 -2.7093118 ]]


In [13]:
A=np.array([[1,2],[3,4]])
print("\nMa trận nghịch đảo của A:")
print(linalg.inv(A))
M=np.array([[-1, 3, 2],
            [0, 2, 1],
            [1, 5, -2]])
print("\nMa trận M:")
print(M)
M_lower=np.tril(M)
print("\nMa trận tam giác dưới của M:")
print(M_lower)


Ma trận nghịch đảo của A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Ma trận M:
[[-1  3  2]
 [ 0  2  1]
 [ 1  5 -2]]

Ma trận tam giác dưới của M:
[[-1  0  0]
 [ 0  2  0]
 [ 1  5 -2]]


In [14]:
M=np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper=np.triu(M)
print(M_upper)

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [15]:
v_diag=np.diag(M)
print(v_diag)

[-1 -2 -2]


In [16]:
M_diag=np.diag(v_diag)
print(M_diag)

[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


Thực hiện tính toán đơn giản trên ma trận

Bài tập dẫn nhập

In [19]:
import sympy as sp
x,y,z=sp.symbols('x y z')
A=sp.Matrix([[2,x**2+2,3],
             [6,0,1],
             [8,z**2+4,y-z]])
B=sp.Matrix([[2,6,3],
             [y-1,0,x+z],
             [2*x**2,5,8]])
eqs=[]
for i in range(3):
    for j in range(3):
        eqs.append(sp.Eq(A[i,j],B[i,j]))
solutions=sp.solve(eqs,(x,y,z),dict=True)
print(solutions)

[{x: 2, y: 7, z: -1}]


3.2/ Các phép biển đổi sơ cấp trên ma trận

In [20]:
A=np.reshape(np.arange(36.0),(6,6))
print(A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [21]:
I6=np.identity(6)
print(I6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [22]:
A.size

36

In [23]:
np.matrix.diagonal(A)

array([ 0.,  7., 14., 21., 28., 35.])

In [24]:
A=A+I6
print(A)

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [25]:
vecB=np.array([1., 2., 3., 4., 5., 6.])
C=A.dot(vecB)
print(C)

[ 71. 198. 325. 452. 579. 706.]


In [26]:
D=np.array([[1., 2., 3., 4., 5., 6.],[1., 0., 1., 0., 1., 0.]])
print(D)

[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]


In [27]:
E=A.dot(D.T)
print(E)

[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [30]:
F=np.array([[1., 1.],[2., 0.],[3., 1.],[4., 0.],[5., 1.],[6., 0.]])
G=A.dot(F)
print(F)
print(G)

[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [34]:
np.linalg.inv(A)

array([[ 0.37022901, -0.45610687, -0.28244275, -0.10877863,  0.0648855 ,
         0.23854962],
       [-0.44656489,  0.65839695, -0.23664122, -0.13167939, -0.02671756,
         0.07824427],
       [-0.26335878, -0.22709924,  0.80916031, -0.15458015, -0.11832061,
        -0.08206107],
       [-0.08015267, -0.11259542, -0.14503817,  0.82251908, -0.20992366,
        -0.24236641],
       [ 0.10305344,  0.0019084 , -0.09923664, -0.20038168,  0.69847328,
        -0.40267176],
       [ 0.28625954,  0.11641221, -0.05343511, -0.22328244, -0.39312977,
         0.4370229 ]])

In [35]:
np.linalg.inv(np.linalg.inv(A))

array([[ 1.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  8.,  8.,  9., 10., 11.],
       [12., 13., 15., 15., 16., 17.],
       [18., 19., 20., 22., 22., 23.],
       [24., 25., 26., 27., 29., 29.],
       [30., 31., 32., 33., 34., 36.]])

 4. Bài toán ứng dụng 2 – Tính toán dãy Fibonacci: Con đường tìm đến tỉ số vàng!

In [36]:
import numpy as np
A=np.array([[1,1],[1,0]])
b=np.array([1, 0])
n=10
for i in range(n):
  b=A.dot(b)
  print(b)

[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


5. Cơ bản về hệ phương trình tuyến tính và ứng dụng minh họa

 5.1. Làm quen với giải hệ phương trình tuyến tính


5.2. Bài toán ứng dụng 3 – Đếm số lượng xe vào khu vực trung tâm

In [37]:
import sympy as sp
from sympy import Symbol
x1=Symbol('x1')
x2=Symbol('x2')
x3=Symbol('x3')
x4=Symbol('x4')
from sympy import solve
pt1=x4+610-450-x1
pt2=x1+400-x2-640
pt3=x2+600-x3
pt4=x3-x4-520
nghiem=sp.solve((pt1,pt2,pt3,pt4))
print(nghiem)

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


In [44]:
import numpy as np
A=np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])
det=np.linalg.det(A)
print("Determinant của A =",det)
if abs(det)>1e-10:
    A_nghichdao=np.linalg.inv(A)
    print("Ma trận nghịch đảo A^-1 là:\n",A_nghichdao)
else:
    print("Ma trận A không khả nghịch, tính ma trận giả nghịch đảo (pseudo-inverse):")
    A_pinv=np.linalg.pinv(A)
    print("Ma trận giả nghịch đảo của A là:\n",A_pinv)

Determinant của A = 0.0
Ma trận A không khả nghịch, tính ma trận giả nghịch đảo (pseudo-inverse):
Ma trận giả nghịch đảo của A là:
 [[-0.375  0.375  0.125 -0.125]
 [-0.125 -0.375  0.375  0.125]
 [ 0.125 -0.125 -0.375  0.375]
 [ 0.375  0.125 -0.125 -0.375]]


BÀI TẬP CHƯƠNG 2


Câu 1: Hãy sử dụng numpy để giải các phương trình sau:

Vấn đề 1 (Problem 1): Tìm điểm giao giữa hai đường thẳng trong ℝ.


In [45]:
import numpy as np
A1=np.array([[1, -1], [2, 3]])
b1=np.array([-2, 6])
x1=np.linalg.solve(A1,b1)
print("Vấn đề 1 - Giao điểm hai đường thẳng:",x1)

Vấn đề 1 - Giao điểm hai đường thẳng: [0. 2.]


Vấn đề 2 (Problem 2): Tìm giao điểm giữa ba mặt phẳng trong ℝ.

In [46]:
A2 = np.array([[1,-1,0],[2,-1,-1],[1,1,1]])
b2 = np.array([2,3,6])
x2 = np.linalg.solve(A2,b2)
print("Vấn đề 2 - Giao điểm ba mặt phẳng:",x2)

Vấn đề 2 - Giao điểm ba mặt phẳng: [3. 1. 2.]


Vấn đề 3 (Problem 3): Tìm các hệ số đa thức để đa thức thỏa các nghiệm.

In [47]:
A3=np.array([[1,1,1],[4,2,1],[9,3,1]])
b3=np.array([4,3,6])
x3=np.linalg.solve(A3,b3)
print("Vấn đề 3 - Hệ số của đa thức ax^2 + bx + c:", x3)

Vấn đề 3 - Hệ số của đa thức ax^2 + bx + c: [ 2. -7.  9.]


Vấn đề 4 (Problem 4)Tìm các hệ đa thức khi phân rã để tính tích phân.

In [48]:
A4=np.array([[1,0,1],[1,1,-2],[-2,2,1]])
b4=np.array([1,-3,0])
x4=np.linalg.solve(A4,b4)
print("Vấn đề 4 - Hệ số a, b, c:", x4)

Vấn đề 4 - Hệ số a, b, c: [-0.11111111 -0.66666667  1.11111111]


Câu 2: Hãy viết các câu lệnh của sympy để giải các phương trình ở Câu 1.

In [49]:
import sympy as sp
#Vấn đề 1
x,y=sp.symbols('x y')
eq1=x-y+2
eq2=2*x+3*y-6
sol1=sp.solve([eq1,eq2],(x,y))
print("Vấn đề 1 (sympy):",sol1)
#Vấn đề 2
x,y,z=sp.symbols('x y z')
eq1=x-y-2
eq2=2*x-y-z-3
eq3=x+y+z-6
sol2=sp.solve([eq1,eq2,eq3],(x,y,z))
print("Vấn đề 2 (sympy):",sol2)
#Vấn đề 3
a,b,c=sp.symbols('a b c')
eq1=a+b+c-4
eq2=4*a+2*b+c-3
eq3=9*a+3*b+c-6
sol3=sp.solve([eq1,eq2,eq3],(a,b,c))
print("Vấn đề 3 (sympy):",sol3)
#Vấn đề 4
a,b,c=sp.symbols('a b c')
eq1=a+c-1
eq2=a+b-2*c+3
eq3=-2*a+2*b + c
sol4=sp.solve([eq1,eq2,eq3],(a,b,c))
print("Vấn đề 4 (sympy):",sol4)

Vấn đề 1 (sympy): {x: 0, y: 2}
Vấn đề 2 (sympy): {x: 3, y: 1, z: 2}
Vấn đề 3 (sympy): {a: 2, b: -7, c: 9}
Vấn đề 4 (sympy): {a: -1/9, b: -2/3, c: 10/9}


Câu 3:

In [50]:
import numpy as np
def fibonacci_matrix(k):
    F = np.array([[1, 1],
                  [1, 0]], dtype=object)
    result = np.linalg.matrix_power(F, k)
    return result

def fibonacci(n):
    if n == 0: return 0
    elif n == 1: return 1
    else:
        a, b = 0, 1
        for _ in range(n - 1):
            a, b = b, a + b
        return b
for k in range(11):
    Fk = fibonacci_matrix(k)
    expected = np.array([
        [fibonacci(k+1), fibonacci(k)],
        [fibonacci(k), fibonacci(k-1) if k > 0 else 0]
    ])
    print(f"\nF^{k} =\n{Fk}")
    print("Dự kiến từ Fibonacci:\n", expected)
    print("Khớp:", np.array_equal(Fk, expected))


F^0 =
[[1 0]
 [0 1]]
Dự kiến từ Fibonacci:
 [[1 0]
 [0 0]]
Khớp: False

F^1 =
[[1 1]
 [1 0]]
Dự kiến từ Fibonacci:
 [[1 1]
 [1 0]]
Khớp: True

F^2 =
[[2 1]
 [1 1]]
Dự kiến từ Fibonacci:
 [[2 1]
 [1 1]]
Khớp: True

F^3 =
[[3 2]
 [2 1]]
Dự kiến từ Fibonacci:
 [[3 2]
 [2 1]]
Khớp: True

F^4 =
[[5 3]
 [3 2]]
Dự kiến từ Fibonacci:
 [[5 3]
 [3 2]]
Khớp: True

F^5 =
[[8 5]
 [5 3]]
Dự kiến từ Fibonacci:
 [[8 5]
 [5 3]]
Khớp: True

F^6 =
[[13 8]
 [8 5]]
Dự kiến từ Fibonacci:
 [[13  8]
 [ 8  5]]
Khớp: True

F^7 =
[[21 13]
 [13 8]]
Dự kiến từ Fibonacci:
 [[21 13]
 [13  8]]
Khớp: True

F^8 =
[[34 21]
 [21 13]]
Dự kiến từ Fibonacci:
 [[34 21]
 [21 13]]
Khớp: True

F^9 =
[[55 34]
 [34 21]]
Dự kiến từ Fibonacci:
 [[55 34]
 [34 21]]
Khớp: True

F^10 =
[[89 55]
 [55 34]]
Dự kiến từ Fibonacci:
 [[89 55]
 [55 34]]
Khớp: True
