CHƯƠNG 6: CÁC KHÁI NIỆM: KHÔNG GIAN VECTOR,
TÍCH TRONG VÀ TRỊ RIÊNG, VECTOR RIÊNG

1. Khái niệm về không gian vector và tích trong:

1.1. Tóm tắt lý thuyết

1.2. Tích vô hướng, trực giao và ứng dụng

In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
tich=np.inner(a,b) #tích vô hướng
print(tich)

32


In [2]:
tich1=np.dot(a,b)
print(tich1)
#kết quả giống như np.inner(a,b)

32


In [3]:
import numpy as np
a=np.array([1,2,-3])
chuan2=np.linalg.norm(a)
print(chuan2)

3.7416573867739413


In [4]:
a=np.array([1,2,-3])
chuan1=np.linalg.norm(a,1)
print(chuan1)

6.0


In [5]:

import math
import numpy as np
def chuan(a,p):
    return np.sum(np.abs(a)**p)**(1/p)
a=np.array([1,2,-3])
print(chuan(a,1))

6.0


In [6]:
print( np.linalg.norm(a,1))

6.0


In [7]:
print(chuan(a,2))

3.7416573867739413


In [8]:
print(np.linalg.norm(a,2))

3.7416573867739413


In [9]:
print(chuan(a,3))

3.3019272488946263


In [10]:
print(np.linalg.norm(a,3))

3.3019272488946263


In [11]:
print(chuan(a,1000))

1.0442214818467515


In [13]:
print(np.linalg.norm(a,1000))

inf


- Gói scipy.linalg cũng có hàm norm và sử dụng như numpy.linalg.norm

In [14]:
 from scipy import linalg
 print(linalg.norm(a))

3.7416573867739413


In [15]:
print(linalg.norm(a,100))

3.0


In [17]:
print(linalg.norm(a,1000))

inf


2. Đọc thêm: Tổ hợp tuyến tính

- Tổ hợp tuyến tính (linear combination)

- Bài toán Thiết kế ô tô hoặc chất hàng vào container/tàu thủy

In [18]:
import numpy as np
m=10
v1=np.array([5,-4,3])
v2=np.array([4,3,-2])
v3=np.array([-4,-3,-1])
v4=np.array([-9,8,6])
mi=np.array([2,5,2,1])
M=np.array([v1,v2,v3,v4])
MT=M.transpose()
MT

array([[ 5,  4, -4, -9],
       [-4,  3, -3,  8],
       [ 3, -2, -1,  6]])

In [20]:
v=(1.0/m)*MT.dot(mi)
print(v)

[1.3 0.9 0. ]


3. Tri riêng, vector riêng của ma trận và ứng dụng

3.1.Bài toán dẫn nhập

In [21]:
import numpy as np
#Khai báo ma trận A
A=np.array([[0.998, 0.136],[0.002, 0.864]])
#Khai báo vector v0
v0=np.array([[0.95],[0.05]])
#Tính vector A^100 (sử dụng hàm matrix_power)
A_100=np.linalg.matrix_power(A, 100)
#Tính vector v100 = A^100 * v0
v100=np.dot(A_100,v0)
x100=v100[0,0]
y100=v100[1,0]
print("A^100 =")
print(A_100)
print("\nVector v100 = A^100 * v0:")
print(v100)
print(f"\nx100 = {x100:.5f}, y100 = {y100:.5f}")

A^100 =
[[0.98550725 0.9855069 ]
 [0.01449275 0.0144931 ]]

Vector v100 = A^100 * v0:
[[0.98550723]
 [0.01449277]]

x100 = 0.98551, y100 = 0.01449


- Trạng thái cân bằng (Markov)

In [22]:
#Viết bằng gói numpy
import numpy as np
#Khai báo ma trận chuyển trạng thái A
ma_tran_A=np.array([[0.998, 0.136],[0.002, 0.864]])
#Tính giá trị riêng và vector riêng của A
gia_tri_rieng,vector_rieng=np.linalg.eig(ma_tran_A)
chi_so=np.argmin(np.abs(gia_tri_rieng - 1))
trang_thai_can_bang=vector_rieng[:, chi_so]
trang_thai_can_bang=trang_thai_can_bang/np.sum(trang_thai_can_bang)
ti_le_co_viec,ti_le_that_nghiep=trang_thai_can_bang
print(f"Tỉ lệ có việc làm ổn định (x): {ti_le_co_viec:.5f}")
print(f"Tỉ lệ thất nghiệp ổn định (y): {ti_le_that_nghiep:.5f}")
print(f"=> Tỉ lệ thất nghiệp sau 100 tuần ≈ {ti_le_that_nghiep * 100:.2f}%")

Tỉ lệ có việc làm ổn định (x): 0.98551
Tỉ lệ thất nghiệp ổn định (y): 0.01449
=> Tỉ lệ thất nghiệp sau 100 tuần ≈ 1.45%


In [23]:
#Viết bằng gói sympy
import sympy as sym
x,y=sym.symbols('x y')
xy=sym.Matrix([x,y])
A=sym.Matrix([[1,-68],[1,1]])
v=sym.Matrix([0, 1])
nghiem=sym.solve([A*xy-v])
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


- Ma trận đường chéo là ma trận có các giá trị ngoài đường chéo bằng 0:

3.2.Trị riêng và vector riêng của ma trận

In [25]:
#Cho ma trận A có kích thước n × n
import numpy as np
#Khai báo ma trận A
A=np.array([[1,6],[5,2]])
#Khai báo vector u
u=np.array([[6],[-5]])
#Nhân A với u
result=A@u
#Kiểm tra Au=-4u
expected=-4*u
print("A @ u =\n", result)
print("-4 * u =\n", expected)
print("Hai vector bằng nhau?", np.allclose(result,expected))

A @ u =
 [[-24]
 [ 20]]
-4 * u =
 [[-24]
 [ 20]]
Hai vector bằng nhau? True


In [26]:
#Quy trình tính toán trị riêng của ma trận: Giải hệ Ax=Lambda x hoặc hệ tương ứng
import sympy
x,y,Lambda=sympy.symbols('x y Lambda')
I=sympy.eye(2)
A=sympy.Matrix([[2,3],[3,-6]])
phuongtrinh=sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem=sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])

[-7.000, 3.000]


In [27]:
print(sympy.pretty(nghiem))

[-7, 3]


In [28]:
#Quy trình tính toán vector riêng của ma trận
import numpy as np
A=np.array([[2,3],[3,-6]])
lam=3
I=np.eye(2)
A_lambdaI=A-lam*I
from scipy.linalg import null_space
null_vecs=null_space(A_lambdaI)
print("Vector riêng ứng với λ = 3 là:")
print(null_vecs)

Vector riêng ứng với λ = 3 là:
[[-0.9486833 ]
 [-0.31622777]]


3.3.Ứng dụng của trị riêng và vector riêng

In [29]:
import numpy as np
A=np.array([[2,3],[3,-6]])
D=np.array([[-7,0],[0,3]])
P=np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1=LA.inv(P)
print (P1)

[[-0.3  0.9]
 [ 0.3  0.1]]


In [30]:
print(A.dot(P))

[[ 2.33333333  9.        ]
 [-7.          3.        ]]


In [31]:
print(P.dot(D))

[[ 2.33333333  9.        ]
 [-7.          3.        ]]


In [32]:
print(P@(D**1000)@P1 )

[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]


In [33]:
print(D**2)

[[49  0]
 [ 0  9]]


BÀI TẬP CHƯƠNG 6

In [34]:
#Câu 1
import numpy as np
import math
a=np.array([1,2,3])
mag=np.sqrt(a.dot(a))
print("a:",mag)
mag=np.sqrt(a@a)
print("b:",mag)
mag=np.sqrt(np.inner(a,a))
print("c:",mag)
mag=lambda x:math.sqrt(sum(i**2 for i in x))
print("d:",mag(a))

a: 3.7416573867739413
b: 3.7416573867739413
c: 3.7416573867739413
d: 3.7416573867739413


In [37]:
import numpy as np
a=np.array(list(map(float,input("Nhập vector a (cách nhau dấu cách): ").split())))
b=np.array(list(map(float,input("Nhập vector b (cách nhau dấu cách): ").split())))
c=a-b
d=np.linalg.norm(c)
print(f"\n1) Khoảng cách ||a-b||={d:.6f}")
e=np.dot(a, b)
na=np.linalg.norm(a)
nb=np.linalg.norm(b)
cosθ=np.clip(e/(na*nb),-1.0,1.0)
θ_rad=np.arccos(cosθ)
θ_deg=np.degrees(θ_rad)
print(f"2) Góc θ: {θ_rad:.6f} rad≃{θ_deg:.2f}°")
f=(e/np.dot(b,b))*b
print(f"3) Chiếu trực giao p={f}")

Nhập vector a (cách nhau dấu cách): 243
Nhập vector b (cách nhau dấu cách): 421

1) Khoảng cách ||a-b||=178.000000
2) Góc θ: 0.000000 rad≃0.00°
3) Chiếu trực giao p=[243.]
